# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 909)
        MainWindow.setStyleSheet("background-color: rgb(46, 119, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(40, 440, 241, 91))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(25)
        self.loadButton.setFont(font)
        self.loadButton.setStyleSheet("background-color: rgb(144, 255, 248);")
        self.loadButton.setObjectName("loadButton")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(40, 550, 241, 91))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(25)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("background-color: rgb(213, 201, 66);")
        self.createButton.setObjectName("createButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 721, 161))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "LOAD"))
        self.createButton.setText(_translate("MainWindow", "CREATE"))
        self.label.setText(_translate("MainWindow", "CIRCUIT BUILDER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
