# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 908)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(40, 440, 241, 91))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(25)
        self.loadButton.setFont(font)
        self.loadButton.setStyleSheet("background-color: rgb(162, 162, 162);\n"
"border-radius: 30px;")
        self.loadButton.setObjectName("loadButton")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(40, 550, 241, 91))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(25)
        self.createButton.setFont(font)
        self.createButton.setStyleSheet("background-color: rgb(133, 161, 161);\n"
"border-radius: 30px;l")
        self.createButton.setObjectName("createButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 30, 721, 161))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -30, 1151, 951))
        self.label_2.setStyleSheet("image: url(:/bback/iprincipal.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.loadButton.raise_()
        self.createButton.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "CARGAR"))
        self.createButton.setText(_translate("MainWindow", "CREAR"))
        self.label.setText(_translate("MainWindow", "CIRCUIT BUILDER"))
import source_rc
